###Create virtual env

---

- name: Deploy Noah, Chris, and Mason's Project
  hosts: localhost
  connection: local
  gather_facts: no
  become: yes

  tasks:

  - name: Create directory
    file:
      path: /home/devasc/Desktop/ncmProject
      state: directory

  - name: Install requirements and init venv
    pip:
      virtualenv: /home/devasc/Desktop/ncmProject/
      requirements: https://raw.githubusercontent.com/noahkamenick/381FinalProject/main/requirements.txt


  - name: Clone git repo
    ansible.builtin.git:
      repo: https://github.com/noahkamenick/381FinalProject.git
      dest: /home/devasc/Desktop/ncmProject/repo
      clone: yes
      version: main

  - name: Reset permissions to devasc
    file:
      path: /home/devasc/Desktop/ncmProject/
      owner: devasc
      group: devasc
      mode: '0777'
      recurse: yes
